# Generated by Django 2.1.2 on 2018-10-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
